apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-zqkx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-zqkx
    app.kubernetes.io/part-of: test-app-nrjh
  name: test-component-zqkx
  namespace: build-e2e-iarr-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-zqkx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-zqkx
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images@sha256:d8c560a02416db5fdb31562a44206a1826d2f1cdf2262d2dc68155fedf16641e
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
